# version: '3.8'

# services:
#   db:
#     image: postgis/postgis:latest
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     environment:
#       POSTGRES_DB: restaurant_db
#       POSTGRES_USER: admin
#       POSTGRES_PASSWORD: admin1234
#     ports:
#       - "5432:5432"

# volumes:
#   postgres_data:

version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python restaurants_project/manage.py runserver 0.0.0.0:8000
